# -*- coding: utf-8 -*-
"""sourcecode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19z6_4qRkxzSqPnastrKArto_JJuOKZbO
"""

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("netflix_titles.csv")


# Frequência Absoluta
frequencia_absoluta = df['type'].value_counts()

plt.bar(frequencia_absoluta.index, frequencia_absoluta.values, color=['red', 'blue'])
plt.title("Frequência Absoluta por Tipo")
plt.xlabel("Tipo")
plt.ylabel("Quantidade")
plt.show()

# Frequência Relativa (%)
frequencia_relativa = df['type'].value_counts(normalize=True) * 100

plt.bar(frequencia_relativa.index, frequencia_relativa.values, color=['pink', 'lightblue'])
plt.title("Frequência Relativa por Tipo")
plt.xlabel("Tipo")
plt.ylabel("Percentual (%)")
plt.show()

# Top 5 países
paises = df['country'].dropna().str.split(', ').explode()
top_paises = paises.value_counts().head(5)

plt.barh(top_paises.index, top_paises.values, color='green')
plt.title("Top 5 Países com Mais Títulos")
plt.xlabel("Quantidade")
plt.ylabel("País")
plt.show()

# Lançamentos por Ano (2005 a 2025)
lancamentos_por_ano = df['release_year'].value_counts().sort_index()
lancamentos_filtrados = lancamentos_por_ano.loc[2005:2025]

plt.bar(lancamentos_filtrados.index, lancamentos_filtrados.values, color='orange')
plt.title("Lançamentos por Ano (2005-2025)")
plt.xlabel("Ano de Lançamento")
plt.ylabel("Quantidade")
plt.xticks(rotation=45)
plt.show()

# -----------------------
# Top 5 gêneros
# -----------------------
generos = df['listed_in'].dropna().str.split(', ').explode()
top_generos = generos.value_counts().head(5)

plt.barh(top_generos.index, top_generos.values, color='purple')
plt.title("Top 5 Gêneros")
plt.xlabel("Quantidade")
plt.ylabel("Gênero")
plt.show()